invoke:
  local:
    params:
      apiVersion: 2015-03-31
      endpoint: http://localhost:3011
    functions:
      plateGen:
          name: cvs-svc-doc-gen
          mock: tests/resources/plate-gen-response.json
  remote:
    params:
      apiVersion: 2015-03-31
    functions:
      plateGen:
          name: doc-gen-${BRANCH}
s3:
  local:
    endpoint: http://localhost:7000
    s3ForcePathStyle: true
  remote: {}
mot:
  documentNames:
    vtg6_vtg7: VTG6_VTG7.pdf
  documentDir: CVS
